amcl:
  ros__parameters:
    use_sim_time: True
    scan_topic: scan

    base_frame_id: base_link
    odom_frame_id: odom
    global_frame_id: map

    min_particles: 500
    max_particles: 2000

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 10.0

    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"

      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]

      PathAlign.scale: 32.0
      GoalAlign.scale: 24.0
      PathDist.scale: 32.0
      GoalDist.scale: 24.0

    min_vel_x: 0.0
    max_vel_x: 0.3
    max_vel_theta: 1.0
    acc_lim_x: 2.5
    acc_lim_theta: 3.2

planner_server:
  ros__parameters:
    use_sim_time: True
    planner_plugins: ["GridBased"]

    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

bt_navigator:
  ros__parameters:
    use_sim_time: True

behavior_server:
  ros__parameters:
    use_sim_time: True

map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: ""

# 🔥 GLOBAL COSTMAP
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: True
      global_frame: map
      robot_base_frame: base_link

      resolution: 0.05

      plugins: ["static_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.5

# 🔥 LOCAL COSTMAP
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: True
      global_frame: odom
      robot_base_frame: base_link

      rolling_window: true
      width: 5
      height: 5
      resolution: 0.05

      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan

        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: LaserScan

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.5